// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pMwUYTA7RBQmT2YN2dTR4LTewwFEWcE',
    appId: '1:290550124442:web:3649b44fa713ef27db7423',
    messagingSenderId: '290550124442',
    projectId: 'attendify-4fc90',
    authDomain: 'attendify-4fc90.firebaseapp.com',
    storageBucket: 'attendify-4fc90.firebasestorage.app',
    measurementId: 'G-H4Z7B44G2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEGlcZh5_mBwHfp2xmRHd4mnM2uz4sVUA',
    appId: '1:290550124442:android:dd124c6c7b0b9703db7423',
    messagingSenderId: '290550124442',
    projectId: 'attendify-4fc90',
    storageBucket: 'attendify-4fc90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY14Msglhm_bBChVthHQv_8N9WEJWO0WI',
    appId: '1:290550124442:ios:de7a44a8a1241db7db7423',
    messagingSenderId: '290550124442',
    projectId: 'attendify-4fc90',
    storageBucket: 'attendify-4fc90.firebasestorage.app',
    iosBundleId: 'com.example.absensiGeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY14Msglhm_bBChVthHQv_8N9WEJWO0WI',
    appId: '1:290550124442:ios:de7a44a8a1241db7db7423',
    messagingSenderId: '290550124442',
    projectId: 'attendify-4fc90',
    storageBucket: 'attendify-4fc90.firebasestorage.app',
    iosBundleId: 'com.example.absensiGeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-pMwUYTA7RBQmT2YN2dTR4LTewwFEWcE',
    appId: '1:290550124442:web:b3256870a7978a66db7423',
    messagingSenderId: '290550124442',
    projectId: 'attendify-4fc90',
    authDomain: 'attendify-4fc90.firebaseapp.com',
    storageBucket: 'attendify-4fc90.firebasestorage.app',
    measurementId: 'G-NV3J5M9ZQL',
  );
}
